
/* CONSULTA 22 - PROJETAR O TÍTULO DE TODOS OS ARTIGOS PUBLICADOS E A SIGLA DOS SEUS RESPECTIVOS EVENTOS  - 
USANDO “INNER JOIN” */
SELECT A.TITULO, E.SIGLA
FROM ARTIGO A INNER JOIN EVENTO E ON (A.COD = E.COD);

/* CONSULTA 23 - PROJETAR OS NOMES DE TODOS OS PESQUISADORES E OS TÍTULOS DE SEUS RESPECTIVOS 
ARTIGOS PUBLICADOS NOS IDIOMAS PORTUGUÊS OU INGLÊS  - SEM USAR “INNER JOIN” */
SELECT P.NOME, A.TITULO
FROM PESQUISADOR P, ESCREVE E, ARTIGO A
WHERE P.CPF =  E.CPF AND 
      E.MAT =  A.MAT AND 
      A.IDIOMA IN ('PORTUGUÊS','INGLÊS') ;

/* CONSULTA 24 - PROJETAR OS NOMES DE TODOS OS PESQUISADORES E OS 
TÍTULOS DOS SEUS RESPECTIVOS ARTIGOS PUBLICADOS NOS IDIOMAS PORTUGUÊS OU INGLÊS  
- USANDO “INNER JOIN” */
SELECT P.NOME, A.TITULO
FROM PESQUISADOR P INNER JOIN ESCREVE E ON (P.CPF = E.CPF) 
     INNER JOIN ARTIGO A ON (E.MAT = A.MAT)
WHERE A.IDIOMA IN ('PORTUGUES','INGLES') ;


/* CONSULTA 25 - PROJETAR TODOS OS ARTIGOS (TÍTULOS) E SEUS RESPECTIVOS EVENTOS (SIGLAS) QUANDO PUBLICADOS*/
SELECT A.TITULO, E.SIGLA
FROM ARTIGO A LEFT OUTER JOIN EVENTO E ON (A.COD = E.COD);


/* CONSULTA 26 - PROJETAR TODOS OS ARTIGOS (TÍTULOS) E SEUS RESPECTIVOS EVENTOS (SIGLAS) QUANDO PUBLICADOS*/
SELECT A.TITULO, E.SIGLA
FROM EVENTO E RIGHT OUTER JOIN ARTIGO A ON (A.COD = E.COD);


/* CONSULTA 27 - PROJETAR OS ARTIGOS (TÍTULOS) E SEUS RESPECTIVOS EVENTOS (SIGLAS), 
INCLUINDO OS ARTIGOS NÃO PUBLICADOS E OS EVENTOS SEM ARTIGOS */
SELECT A.TITULO, E.SIGLA
FROM ARTIGO A FULL OUTER JOIN EVENTO E ON (A.COD = E.COD);


/* CONSULTA 28  - PROJETAR OS EVENTO (SIGLAS) SEM ARTIGOS PUBLICADOS (NULL PARA TÍTULO DO ARTIGO) 
– USANDO “LEFT OUTER JOIN” */
SELECT E.SIGLA, A.TITULO
FROM EVENTO E LEFT OUTER JOIN ARTIGO A ON (E.COD = A.COD)
WHERE A.COD IS NULL;

/* CONSULTA 29  - PROJETAR OS EVENTO (SIGLAS) SEM ARTIGOS PUBLICADOS (NULL PARA TÍTULO DO ARTIGO) 
- USANDO “RIGTH OUTER JOIN” */
SELECT E.SIGLA, A.TITULO
FROM ARTIGO A RIGHT OUTER JOIN EVENTO E ON (E.COD = A.COD)
WHERE A.COD IS NULL;

/* CONSULTA 30  - PROJETAR OS ARTIGOS (TÍTULOS) NÃO PUBLICADOS E OS EVENTOS (SIGLAS) SEM ARTIGOS 
- USANDO “FULL OUTER JOIN” */
SELECT A.TITULO, E.SIGLA
FROM ARTIGO A FULL OUTER JOIN EVENTO E ON (A.COD = E.COD)
WHERE  A.COD IS NULL OR E.COD IS NULL;


/* CONSULTA 31  - PARA CADA PESQUISADOR, PROJETAR SEU NOME E 
OS NOMES DOS PESQUISADORES MAIS NOVOS DO QUE ELE */
SELECT P1.NOME, P2.NOME
FROM PESQUISADOR P1 INNER JOIN PESQUISADOR P2 ON (P1.NASCIMENTO < P2.NASCIMENTO);


/* CONSULTA 32 - PROJETAR O NOME E O NASCIMENTO DOS PESQUISADORES EM 
ORDEM DECRESCENTE DO NASCIMENTO. PARA DATAS IGUAIS, 
CONSIDERAR A ORDEM ALFABÉTICA DO NOME DO PESQUISADOR */
SELECT NOME, NASCIMENTO
FROM PESQUISADOR
ORDER BY NASCIMENTO DESC, NOME ASC;


-- CONSULTA 33 - PROJETAR A MÉDIA DAS NOTAS DOS ARTIGOS POR EVENTO
SELECT E.SIGLA, AVG (A.NOTA) AS MEDIA_NOTA
FROM ARTIGO A INNER JOIN EVENTO E ON (A.COD = E. COD)
GROUP BY E.SIGLA;


/* CONSULTA 34 - PROJETAR AS SIGLAS DOS EVENTOS CUJAS MÉDIAS DAS NOTAS DOS ARTIGOS SÃO MAIORES DO QUE 8 */
SELECT E.SIGLA, AVG (A.NOTA) 
FROM EVENTO E INNER JOIN ARTIGO A  ON (E.COD = A. COD)
GROUP BY E.SIGLA 
HAVING AVG (A.NOTA) > 8;


/* CONSULTA 35 - PROJETAR OS NOMES DOS PESQUISADORES QUE PUBLICARAM MAIS DE 3 ARTIGOS */
SELECT P.NOME, COUNT(*) 
FROM PESQUISADOR P INNER JOIN ESCREVE E ON (P.CPF = E.CPF) 
GROUP BY P.NOME
HAVING COUNT(*) > 3;


/* CONSULTA 36 - PROJETAR OS TÍTULOS DOS ARTIGOS COM NOTA  ACIMA DA MÉDIA */
SELECT TITULO
FROM ARTIGO
WHERE NOTA > 
            (SELECT AVG (NOTA)
            FROM ARTIGO) ;


/* CONSULTA 37 - PROJETAR OS NOMES DOS PESQUISADORES QUE POSSUEM ARTIGOS SEM NOTA - USANDO “IN” E “INNER JOIN”) */
SELECT NOME
FROM PESQUISADOR 
WHERE CPF NOT IN
                (SELECT CPF
                FROM ESCREVE E INNER JOIN ARTIGO A ON E.MAT =  A.MAT
                WHERE NOTA IS NOT NULL);


/* CONSULTA 38 - PROJETAR OS NOMES DOS PESQUISADORES QUE NASCERAM NO MESMO ANO E TRABALHAM NA MESMA INSTITUIÇÃO DO PESQUISADOR '1111' */
SELECT NOME
FROM PESQUISADOR 
WHERE (INSTITUICAO,TO_CHAR(NASCIMENTO,'YY')) = (SELECT INSTITUICAO,TO_CHAR(NASCIMENTO,'YY')
		    FROM PESQUISADOR
		    WHERE CPF = '1111');

            
/* CONSULTA 39 - POR INSTITUIÇÃO, PROJETAR O NOME E A INSTITUIÇÃO DOS PESQUISADORES MAIS VELHOS */
SELECT NOME, INSTITUICAO
FROM PESQUISADOR
WHERE (INSTITUICAO, TO_CHAR(NASCIMENTO,'YY')) IN 
     (SELECT INSTITUICAO, MIN(TO_CHAR(NASCIMENTO,'YY'))
      FROM PESQUISADOR
      GROUP BY INSTITUICAO)
ORDER BY INSTITUICAO;
